
 Network vyctor-nestjs_rinha  Creating
 Network vyctor-nestjs_rinha  Created
 Container vyctor-nestjs-cache-1  Creating
 Container vyctor-nestjs-postgres-1  Creating
 Container vyctor-nestjs-cache-1  Created
 Container vyctor-nestjs-postgres-1  Created
 Container vyctor-nestjs-api01-1  Creating
 Container vyctor-nestjs-api02-1  Creating
 Container vyctor-nestjs-api01-1  Created
 Container vyctor-nestjs-api02-1  Created
 Container vyctor-nestjs-nginx-1  Creating
 Container vyctor-nestjs-nginx-1  Created
Attaching to api01-1, api02-1, cache-1, nginx-1, postgres-1
cache-1  | 1:C 19 Aug 2025 20:15:56.918 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cache-1  | 1:C 19 Aug 2025 20:15:56.918 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache-1  | 1:C 19 Aug 2025 20:15:56.918 * Redis version=7.2.10, bits=64, commit=00000000, modified=0, pid=1, just started
cache-1  | 1:C 19 Aug 2025 20:15:56.918 * Configuration loaded
cache-1  | 1:M 19 Aug 2025 20:15:56.919 * monotonic clock: POSIX clock_gettime
cache-1  | 1:M 19 Aug 2025 20:15:56.920 * Running mode=standalone, port=6379.
cache-1  | 1:M 19 Aug 2025 20:15:56.920 * Server initialized
cache-1  | 1:M 19 Aug 2025 20:15:56.920 * Ready to accept connections tcp
postgres-1  | The files belonging to this database system will be owned by user "postgres".
postgres-1  | This user must also own the server process.
postgres-1  | 
postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
postgres-1  | The default database encoding has accordingly been set to "UTF8".
postgres-1  | The default text search configuration will be set to "english".
postgres-1  | 
postgres-1  | Data page checksums are enabled.
postgres-1  | 
postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
postgres-1  | creating subdirectories ... ok
postgres-1  | selecting dynamic shared memory implementation ... posix
postgres-1  | selecting default "max_connections" ... 100
postgres-1  | selecting default "shared_buffers" ... 128MB
postgres-1  | selecting default time zone ... Etc/UTC
postgres-1  | creating configuration files ... ok
nginx-1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1     | /docker-entrypoint.sh: Configuration complete; ready for start up
postgres-1  | running bootstrap script ... ok
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[NestFactory] [39m[32mStarting Nest application...[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[NestFactory] [39m[32mStarting Nest application...[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mAppModule dependencies initialized[39m[38;5;3m +110ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmModule dependencies initialized[39m[38;5;3m +0ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mConfigHostModule dependencies initialized[39m[38;5;3m +1ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mHttpModule dependencies initialized[39m[38;5;3m +0ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mDiscoveryModule dependencies initialized[39m[38;5;3m +0ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mConfigModule dependencies initialized[39m[38;5;3m +1ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mCqrsModule dependencies initialized[39m[38;5;3m +1ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mScheduleModule dependencies initialized[39m[38;5;3m +0ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mConfigModule dependencies initialized[39m[38;5;3m +0ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mAppModule dependencies initialized[39m[38;5;3m +200ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmModule dependencies initialized[39m[38;5;3m +1ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mConfigHostModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mHttpModule dependencies initialized[39m[38;5;3m +1ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mDiscoveryModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mConfigModule dependencies initialized[39m[38;5;3m +1ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mCqrsModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mScheduleModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mConfigModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mInfraModule dependencies initialized[39m[38;5;3m +33ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +3ms[39m
api02-1     | [31m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (1)...[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mInfraModule dependencies initialized[39m[38;5;3m +92ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +0ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +3ms[39m
api01-1     | [31m[Nest] 1  - [39m08/19/2025, 8:16:00 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (1)...[39m
api01-1     | Error: connect ECONNREFUSED 172.20.0.3:5432
api01-1     |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)
api02-1     | Error: connect ECONNREFUSED 172.20.0.3:5432
api02-1     |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)
nginx-1     | 2025/08/19 20:16:01 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.4:8080/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/19 20:16:01 [warn] 30#30: *1 upstream server temporarily disabled while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.4:8080/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/19 20:16:01 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.5:8080/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/19 20:16:01 [warn] 30#30: *1 upstream server temporarily disabled while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.5:8080/payments-summary", host: "localhost:9999"
postgres-1  | performing post-bootstrap initialization ... ok
postgres-1  | syncing data to disk ... ok
postgres-1  | 
postgres-1  | 
postgres-1  | Success. You can now start the database server using:
postgres-1  | 
postgres-1  |     pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start
postgres-1  | 
postgres-1  | initdb: warning: enabling "trust" authentication for local connections
postgres-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres-1  | waiting for server to start....2025-08-19 20:16:01.946 UTC [49] LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg130+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
postgres-1  | 2025-08-19 20:16:01.949 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2025-08-19 20:16:01.961 UTC [52] LOG:  database system was shut down at 2025-08-19 20:16:01 UTC
postgres-1  | 2025-08-19 20:16:01.969 UTC [49] LOG:  database system is ready to accept connections
postgres-1  |  done
postgres-1  | server started
postgres-1  | CREATE DATABASE
postgres-1  | 
postgres-1  | 
postgres-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres-1  | 
postgres-1  | waiting for server to shut down...2025-08-19 20:16:02.544 UTC [49] LOG:  received fast shutdown request
postgres-1  | .2025-08-19 20:16:02.548 UTC [49] LOG:  aborting any active transactions
postgres-1  | 2025-08-19 20:16:02.550 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgres-1  | 2025-08-19 20:16:02.550 UTC [50] LOG:  shutting down
postgres-1  | 2025-08-19 20:16:02.553 UTC [50] LOG:  checkpoint starting: shutdown immediate
postgres-1  | 2025-08-19 20:16:02.665 UTC [50] LOG:  checkpoint complete: wrote 925 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.095 s, sync=0.008 s, total=0.115 s; sync files=301, longest=0.003 s, average=0.001 s; distance=4256 kB, estimate=4256 kB; lsn=0/1B5E128, redo lsn=0/1B5E128
postgres-1  | 2025-08-19 20:16:02.675 UTC [49] LOG:  database system is shut down
postgres-1  |  done
postgres-1  | server stopped
postgres-1  | 
postgres-1  | PostgreSQL init process complete; ready for start up.
postgres-1  | 
postgres-1  | 2025-08-19 20:16:02.773 UTC [1] LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg130+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
postgres-1  | 2025-08-19 20:16:02.773 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1  | 2025-08-19 20:16:02.773 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1  | 2025-08-19 20:16:02.779 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2025-08-19 20:16:02.788 UTC [65] LOG:  database system was shut down at 2025-08-19 20:16:02 UTC
postgres-1  | 2025-08-19 20:16:02.851 UTC [1] LOG:  database system is ready to accept connections
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmCoreModule dependencies initialized[39m[38;5;3m +3103ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmModule dependencies initialized[39m[38;5;3m +0ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mPaymentsModule dependencies initialized[39m[38;5;3m +1ms[39m
postgres-1  | 2025-08-19 20:16:04.133 UTC [70] ERROR:  relation "payments" already exists
postgres-1  | 2025-08-19 20:16:04.133 UTC [70] STATEMENT:  CREATE TABLE "payments" ("id" SERIAL NOT NULL, "correlationId" character varying NOT NULL, "gateway" character varying NOT NULL, "amount" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9965e60c5cd2b29271b36657bd2" UNIQUE ("correlationId"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))
api02-1     | [31m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (2)...[39m
api02-1     | QueryFailedError: relation "payments" already exists
api02-1     |     at PostgresQueryRunner.query (/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:19)
api02-1     |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
api02-1     |     at async PostgresQueryRunner.executeQueries (/node_modules/typeorm/query-runner/BaseQueryRunner.js:441:13)
api02-1     |     at async PostgresQueryRunner.createTable (/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:426:9)
api02-1     |     at async RdbmsSchemaBuilder.createNewTables (/node_modules/typeorm/schema-builder/RdbmsSchemaBuilder.js:418:13)
api02-1     |     at async RdbmsSchemaBuilder.executeSchemaSyncOperationsInProperOrder (/node_modules/typeorm/schema-builder/RdbmsSchemaBuilder.js:167:9)
api02-1     |     at async RdbmsSchemaBuilder.build (/node_modules/typeorm/schema-builder/RdbmsSchemaBuilder.js:66:13)
api02-1     |     at async DataSource.synchronize (/node_modules/typeorm/data-source/DataSource.js:212:9)
api02-1     |     at async DataSource.initialize (/node_modules/typeorm/data-source/DataSource.js:157:17)
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[RoutesResolver] [39m[32mPaymentsController {/payments}:[39m[38;5;3m +47ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[RouterExplorer] [39m[32mMapped {/payments, POST} route[39m[38;5;3m +5ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[RouterExplorer] [39m[32mMapped {/payments/purge, POST} route[39m[38;5;3m +2ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[RoutesResolver] [39m[32mPaymentsSummaryController {/payments-summary}:[39m[38;5;3m +0ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[RouterExplorer] [39m[32mMapped {/payments-summary, GET} route[39m[38;5;3m +1ms[39m
api01-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:04 PM [32m    LOG[39m [38;5;3m[NestApplication] [39m[32mNest application successfully started[39m[38;5;3m +33ms[39m
api01-1     | Application is running on: http://localhost:8080
nginx-1     | 2025/08/19 20:16:06 [error] 30#30: *4 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmCoreModule dependencies initialized[39m[38;5;3m +3044ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmModule dependencies initialized[39m[38;5;3m +0ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mPaymentsModule dependencies initialized[39m[38;5;3m +1ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[RoutesResolver] [39m[32mPaymentsController {/payments}:[39m[38;5;3m +16ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[RouterExplorer] [39m[32mMapped {/payments, POST} route[39m[38;5;3m +6ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[RouterExplorer] [39m[32mMapped {/payments/purge, POST} route[39m[38;5;3m +21ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[RoutesResolver] [39m[32mPaymentsSummaryController {/payments-summary}:[39m[38;5;3m +1ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[RouterExplorer] [39m[32mMapped {/payments-summary, GET} route[39m[38;5;3m +1ms[39m
api02-1     | [32m[Nest] 1  - [39m08/19/2025, 8:16:07 PM [32m    LOG[39m [38;5;3m[NestApplication] [39m[32mNest application successfully started[39m[38;5;3m +15ms[39m
api02-1     | Application is running on: http://localhost:8080
nginx-1     | 2025/08/19 20:16:11 [error] 30#30: *5 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
api01-1     | Error: read ECONNRESET
api01-1     |     at TCP.onStreamRead (node:internal/stream_base_commons:216:20) {
api01-1     |   errno: -104,
api01-1     |   code: 'ECONNRESET',
api01-1     |   syscall: 'read'
api01-1     | }
api01-1     | Error: read ECONNRESET
api01-1     |     at TCP.onStreamRead (node:internal/stream_base_commons:216:20) {
api01-1     |   errno: -104,
api01-1     |   code: 'ECONNRESET',
api01-1     |   syscall: 'read'
api01-1     | }
api02-1     | Error: read ECONNRESET
api02-1     |     at TCP.onStreamRead (node:internal/stream_base_commons:216:20) {
api02-1     |   errno: -104,
api02-1     |   code: 'ECONNRESET',
api02-1     |   syscall: 'read'
api02-1     | }
api01-1     | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 172.20.0.2:6379
api01-1     |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)
api02-1     | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 172.20.0.2:6379
api02-1     |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16)
[Kcache-1 exited with code 137
api01-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api02-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api01-1     | Error: connect ETIMEDOUT
api01-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api01-1     |     at Object.onceWrapper (node:events:621:28)
api01-1     |     at Socket.emit (node:events:507:28)
api01-1     |     at Socket._onTimeout (node:net:604:8)
api01-1     |     at listOnTimeout (node:internal/timers:608:17)
api01-1     |     at process.processTimers (node:internal/timers:543:7) {
api01-1     |   errorno: 'ETIMEDOUT',
api01-1     |   code: 'ETIMEDOUT',
api01-1     |   syscall: 'connect'
api01-1     | }
api02-1     | Error: connect ETIMEDOUT
api02-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api02-1     |     at Object.onceWrapper (node:events:621:28)
api02-1     |     at Socket.emit (node:events:507:28)
api02-1     |     at Socket._onTimeout (node:net:604:8)
api02-1     |     at listOnTimeout (node:internal/timers:608:17)
api02-1     |     at process.processTimers (node:internal/timers:543:7) {
api02-1     |   errorno: 'ETIMEDOUT',
api02-1     |   code: 'ETIMEDOUT',
api02-1     |   syscall: 'connect'
api02-1     | }
api01-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api02-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api01-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api02-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api01-1     | [ioredis] Unhandled error event: Error: connect ETIMEDOUT
api01-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api01-1     |     at Object.onceWrapper (node:events:621:28)
api01-1     |     at Socket.emit (node:events:507:28)
api01-1     |     at Socket._onTimeout (node:net:604:8)
api01-1     |     at listOnTimeout (node:internal/timers:608:17)
api01-1     |     at process.processTimers (node:internal/timers:543:7)
api02-1     | [ioredis] Unhandled error event: Error: connect ETIMEDOUT
api02-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api02-1     |     at Object.onceWrapper (node:events:621:28)
api02-1     |     at Socket.emit (node:events:507:28)
api02-1     |     at Socket._onTimeout (node:net:604:8)
api02-1     |     at listOnTimeout (node:internal/timers:608:17)
api02-1     |     at process.processTimers (node:internal/timers:543:7)
api01-1     | Error: connect ETIMEDOUT
api01-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api01-1     |     at Object.onceWrapper (node:events:621:28)
api01-1     |     at Socket.emit (node:events:507:28)
api01-1     |     at Socket._onTimeout (node:net:604:8)
api01-1     |     at listOnTimeout (node:internal/timers:608:17)
api01-1     |     at process.processTimers (node:internal/timers:543:7) {
api01-1     |   errorno: 'ETIMEDOUT',
api01-1     |   code: 'ETIMEDOUT',
api01-1     |   syscall: 'connect'
api01-1     | }
api02-1     | Error: connect ETIMEDOUT
api02-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api02-1     |     at Object.onceWrapper (node:events:621:28)
api02-1     |     at Socket.emit (node:events:507:28)
api02-1     |     at Socket._onTimeout (node:net:604:8)
api02-1     |     at listOnTimeout (node:internal/timers:608:17)
api02-1     |     at process.processTimers (node:internal/timers:543:7) {
api02-1     |   errorno: 'ETIMEDOUT',
api02-1     |   code: 'ETIMEDOUT',
api02-1     |   syscall: 'connect'
api02-1     | }
api02-1     | Error: connect ETIMEDOUT
api02-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api02-1     |     at Object.onceWrapper (node:events:621:28)
api02-1     |     at Socket.emit (node:events:507:28)
api02-1     |     at Socket._onTimeout (node:net:604:8)
api02-1     |     at listOnTimeout (node:internal/timers:608:17)
api02-1     |     at process.processTimers (node:internal/timers:543:7) {
api02-1     |   errorno: 'ETIMEDOUT',
api02-1     |   code: 'ETIMEDOUT',
api02-1     |   syscall: 'connect'
api02-1     | }
api01-1     | Error: connect ETIMEDOUT
api01-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api01-1     |     at Object.onceWrapper (node:events:621:28)
api01-1     |     at Socket.emit (node:events:507:28)
api01-1     |     at Socket._onTimeout (node:net:604:8)
api01-1     |     at listOnTimeout (node:internal/timers:608:17)
api01-1     |     at process.processTimers (node:internal/timers:543:7) {
api01-1     |   errorno: 'ETIMEDOUT',
api01-1     |   code: 'ETIMEDOUT',
api01-1     |   syscall: 'connect'
api01-1     | }
api02-1     | Error: connect ETIMEDOUT
api02-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api02-1     |     at Object.onceWrapper (node:events:621:28)
api02-1     |     at Socket.emit (node:events:507:28)
api02-1     |     at Socket._onTimeout (node:net:604:8)
api02-1     |     at listOnTimeout (node:internal/timers:608:17)
api02-1     |     at process.processTimers (node:internal/timers:543:7) {
api02-1     |   errorno: 'ETIMEDOUT',
api02-1     |   code: 'ETIMEDOUT',
api02-1     |   syscall: 'connect'
api02-1     | }
api01-1     | Error: connect ETIMEDOUT
api01-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api01-1     |     at Object.onceWrapper (node:events:621:28)
api01-1     |     at Socket.emit (node:events:507:28)
api01-1     |     at Socket._onTimeout (node:net:604:8)
api01-1     |     at listOnTimeout (node:internal/timers:608:17)
api01-1     |     at process.processTimers (node:internal/timers:543:7) {
api01-1     |   errorno: 'ETIMEDOUT',
api01-1     |   code: 'ETIMEDOUT',
api01-1     |   syscall: 'connect'
api01-1     | }
postgres-1  | 2025-08-19 20:21:02.878 UTC [63] LOG:  checkpoint starting: time
api02-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api01-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api02-1     | Error: connect ETIMEDOUT
api02-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api02-1     |     at Object.onceWrapper (node:events:621:28)
api02-1     |     at Socket.emit (node:events:507:28)
api02-1     |     at Socket._onTimeout (node:net:604:8)
api02-1     |     at listOnTimeout (node:internal/timers:608:17)
api02-1     |     at process.processTimers (node:internal/timers:543:7) {
api02-1     |   errorno: 'ETIMEDOUT',
api02-1     |   code: 'ETIMEDOUT',
api02-1     |   syscall: 'connect'
api02-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api02-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api02-1     | Error: connect ETIMEDOUT
api02-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api02-1     |     at Object.onceWrapper (node:events:621:28)
api02-1     |     at Socket.emit (node:events:507:28)
api02-1     |     at Socket._onTimeout (node:net:604:8)
api02-1     |     at listOnTimeout (node:internal/timers:608:17)
api02-1     |     at process.processTimers (node:internal/timers:543:7) {
api02-1     |   errorno: 'ETIMEDOUT',
api02-1     |   code: 'ETIMEDOUT',
api02-1     |   syscall: 'connect'
api02-1     | }
api01-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
api01-1     | Error: getaddrinfo EAI_AGAIN cache
api01-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api01-1     |   errno: -3001,
api01-1     |   code: 'EAI_AGAIN',
api01-1     |   syscall: 'getaddrinfo',
api01-1     |   hostname: 'cache'
api01-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
[Knginx-1 exited with code 0
api02-1     | [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26)
api01-1     | Error: connect ETIMEDOUT
api01-1     |     at Socket.<anonymous> (/node_modules/ioredis/built/Redis.js:170:41)
api01-1     |     at Object.onceWrapper (node:events:621:28)
api01-1     |     at Socket.emit (node:events:507:28)
api01-1     |     at Socket._onTimeout (node:net:604:8)
api01-1     |     at listOnTimeout (node:internal/timers:608:17)
api01-1     |     at process.processTimers (node:internal/timers:543:7) {
api01-1     |   errorno: 'ETIMEDOUT',
api01-1     |   code: 'ETIMEDOUT',
api01-1     |   syscall: 'connect'
api01-1     | }
api02-1     | Error: getaddrinfo EAI_AGAIN cache
api02-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
api02-1     |   errno: -3001,
api02-1     |   code: 'EAI_AGAIN',
api02-1     |   syscall: 'getaddrinfo',
api02-1     |   hostname: 'cache'
api02-1     | }
[Kapi02-1 exited with code 137
[Kapi01-1 exited with code 137
postgres-1  | 2025-08-19 20:21:43.371 UTC [1] LOG:  received fast shutdown request
postgres-1  | 2025-08-19 20:21:43.375 UTC [1] LOG:  aborting any active transactions
postgres-1  | 2025-08-19 20:21:43.378 UTC [1] LOG:  background worker "logical replication launcher" (PID 68) exited with exit code 1
postgres-1  | 2025-08-19 20:21:43.390 UTC [63] LOG:  checkpoint complete: wrote 594 buffers (3.6%); 0 WAL file(s) added, 0 removed, 1 recycled; write=40.483 s, sync=0.005 s, total=40.513 s; sync files=58, longest=0.005 s, average=0.001 s; distance=8268 kB, estimate=8268 kB; lsn=0/2371588, redo lsn=0/23714F8
postgres-1  | 2025-08-19 20:21:43.390 UTC [63] LOG:  shutting down
postgres-1  | 2025-08-19 20:21:43.393 UTC [63] LOG:  checkpoint starting: shutdown immediate
postgres-1  | 2025-08-19 20:21:43.403 UTC [63] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.000 s, total=0.013 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=7442 kB; lsn=0/2371600, redo lsn=0/2371600
postgres-1  | 2025-08-19 20:21:43.412 UTC [1] LOG:  database system is shut down
log truncated at line 1000
