
 Network willianmarquess-node_backend  Creating
 Network willianmarquess-node_backend  Created
 Container redis  Creating
 Container redis  Created
 Container willianmarquess-node-service2-1  Creating
 Container willianmarquess-node-service1-1  Creating
 Container willianmarquess-node-service2-1  Created
 Container willianmarquess-node-service1-1  Created
 Container willianmarquess-node-nginx-1  Creating
 Container willianmarquess-node-nginx-1  Created
Attaching to redis, nginx-1, service1-1, service2-1
redis  | Starting Redis Server
redis  | 1:C 19 Aug 2025 21:10:50.228 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis  | 1:C 19 Aug 2025 21:10:50.228 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis  | 1:C 19 Aug 2025 21:10:50.228 * Redis version=8.2.0, bits=64, commit=00000000, modified=1, pid=1, just started
redis  | 1:C 19 Aug 2025 21:10:50.228 * Configuration loaded
redis  | 1:M 19 Aug 2025 21:10:50.229 * monotonic clock: POSIX clock_gettime
redis  | 1:M 19 Aug 2025 21:10:50.320 * Running mode=standalone, port=6379.
redis  | 1:M 19 Aug 2025 21:10:50.320 * <bf> RedisBloom version 8.2.0 (Git=unknown)
redis  | 1:M 19 Aug 2025 21:10:50.320 * <bf> Registering configuration options: [
redis  | 1:M 19 Aug 2025 21:10:50.320 * <bf> 	{ bf-error-rate       :      0.01 }
redis  | 1:M 19 Aug 2025 21:10:50.320 * <bf> 	{ bf-initial-size     :       100 }
redis  | 1:M 19 Aug 2025 21:10:50.320 * <bf> 	{ bf-expansion-factor :         2 }
redis  | 1:M 19 Aug 2025 21:10:50.320 * <bf> 	{ cf-bucket-size      :         2 }
redis  | 1:M 19 Aug 2025 21:10:50.320 * <bf> 	{ cf-initial-size     :      1024 }
redis  | 1:M 19 Aug 2025 21:10:50.320 * <bf> 	{ cf-max-iterations   :        20 }
redis  | 1:M 19 Aug 2025 21:10:50.321 * <bf> 	{ cf-expansion-factor :         1 }
redis  | 1:M 19 Aug 2025 21:10:50.321 * <bf> 	{ cf-max-expansions   :        32 }
redis  | 1:M 19 Aug 2025 21:10:50.321 * <bf> ]
redis  | 1:M 19 Aug 2025 21:10:50.321 * Module 'bf' loaded from /usr/local/lib/redis/modules//redisbloom.so
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> Redis version found by RedisSearch : 8.2.0 - oss
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> RediSearch version 8.2.0 (Git=d81ebce)
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> Low level api version 1 initialized successfully
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> gc: ON, prefix min length: 2, min word length to stem: 4, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000, 
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> Initialized thread pools!
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> Disabled workers threadpool of size 0
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> Subscribe to config changes
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> Enabled role change notification
redis  | 1:M 19 Aug 2025 21:10:50.326 * <search> Cluster configuration: AUTO partitions, type: 0, coordinator timeout: 0ms
redis  | 1:M 19 Aug 2025 21:10:50.327 * <search> Register write commands
redis  | 1:M 19 Aug 2025 21:10:50.327 * Module 'search' loaded from /usr/local/lib/redis/modules//redisearch.so
redis  | 1:M 19 Aug 2025 21:10:50.327 * <timeseries> RedisTimeSeries version 80200, git_sha=1439d4a439ca9c063e6ef124a510abff09a5d493
redis  | 1:M 19 Aug 2025 21:10:50.327 * <timeseries> Redis version found by RedisTimeSeries : 8.2.0 - oss
redis  | 1:M 19 Aug 2025 21:10:50.327 * <timeseries> Registering configuration options: [
redis  | 1:M 19 Aug 2025 21:10:50.327 * <timeseries> 	{ ts-compaction-policy   :              }
redis  | 1:M 19 Aug 2025 21:10:50.327 * <timeseries> 	{ ts-num-threads         :            3 }
redis  | 1:M 19 Aug 2025 21:10:50.327 * <timeseries> 	{ ts-retention-policy    :            0 }
redis  | 1:M 19 Aug 2025 21:10:50.328 * <timeseries> 	{ ts-duplicate-policy    :        block }
redis  | 1:M 19 Aug 2025 21:10:50.328 * <timeseries> 	{ ts-chunk-size-bytes    :         4096 }
redis  | 1:M 19 Aug 2025 21:10:50.328 * <timeseries> 	{ ts-encoding            :   compressed }
redis  | 1:M 19 Aug 2025 21:10:50.328 * <timeseries> 	{ ts-ignore-max-time-diff:            0 }
redis  | 1:M 19 Aug 2025 21:10:50.328 * <timeseries> 	{ ts-ignore-max-val-diff :     0.000000 }
redis  | 1:M 19 Aug 2025 21:10:50.328 * <timeseries> ]
redis  | 1:M 19 Aug 2025 21:10:50.328 * <timeseries> Detected redis oss
redis  | 1:M 19 Aug 2025 21:10:50.328 * <timeseries> Enabled diskless replication
redis  | 1:M 19 Aug 2025 21:10:50.328 * Module 'timeseries' loaded from /usr/local/lib/redis/modules//redistimeseries.so
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> Created new data type 'ReJSON-RL'
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> version: 80200 git sha: unknown branch: unknown
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> Exported RedisJSON_V1 API
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> Exported RedisJSON_V2 API
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> Exported RedisJSON_V3 API
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> Exported RedisJSON_V4 API
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> Exported RedisJSON_V5 API
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> Enabled diskless replication
redis  | 1:M 19 Aug 2025 21:10:50.329 * <ReJSON> Initialized shared string cache, thread safe: false.
redis  | 1:M 19 Aug 2025 21:10:50.329 * Module 'ReJSON' loaded from /usr/local/lib/redis/modules//rejson.so
redis  | 1:M 19 Aug 2025 21:10:50.329 * <search> Acquired RedisJSON_V5 API
redis  | 1:M 19 Aug 2025 21:10:50.330 * Server initialized
redis  | 1:M 19 Aug 2025 21:10:50.330 * Ready to accept connections tcp
service1-1  | [CACHE] Connected with success.
service1-1  | App rodando uwebsockets ðŸ”¥
service2-1  | [CACHE] Connected with success.
service2-1  | App rodando uwebsockets ðŸ”¥
service1-1  | [CACHE] Connected with success.
service2-1  | [CACHE] Connected with success.
nginx-1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1     | /docker-entrypoint.sh: Configuration complete; ready for start up
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service2-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service2-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service2-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service2-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service2-1  |     at listOnTimeout (node:internal/timers:588:17)
service2-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
service1-1  |     at Timeout._onTimeout (file:///app/src/utils/fetchWithTimeout.js:15:37)
service1-1  |     at listOnTimeout (node:internal/timers:588:17)
service1-1  |     at process.processTimers (node:internal/timers:523:7)
service1-1  | fetchWithTimeout DOMException [AbortError]: This operation was aborted
service1-1  |     at new DOMException (node:internal/per_context/domexception:66:5)
service1-1  |     at AbortController.abort (node:internal/abort_controller:504:18)
log truncated at line 1000
