
 Network jessicanathany-dotnet_backend_network  Creating
 Network jessicanathany-dotnet_backend_network  Created
 Container backend_database  Creating
 Container backend_database  Created
 Container backend-api-2  Creating
 Container backend-api-1  Creating
 Container backend-api-1  Created
 Container backend-api-2  Created
 Container load_balancer  Creating
 Container load_balancer  Created
Attaching to backend-api-1, backend-api-2, backend_database, load_balancer
backend_database  | The files belonging to this database system will be owned by user "postgres".
backend_database  | This user must also own the server process.
backend_database  | 
backend_database  | The database cluster will be initialized with locale "en_US.utf8".
backend_database  | The default database encoding has accordingly been set to "UTF8".
backend_database  | The default text search configuration will be set to "english".
backend_database  | 
backend_database  | Data page checksums are disabled.
backend_database  | 
backend_database  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
backend_database  | creating subdirectories ... ok
backend_database  | selecting dynamic shared memory implementation ... posix
backend_database  | selecting default "max_connections" ... 100
backend_database  | selecting default "shared_buffers" ... 128MB
backend_database  | selecting default time zone ... UTC
backend_database  | creating configuration files ... ok
load_balancer     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
load_balancer     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
load_balancer     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
load_balancer     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
load_balancer     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
load_balancer     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
load_balancer     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
load_balancer     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
load_balancer     | /docker-entrypoint.sh: Configuration complete; ready for start up
backend_database  | running bootstrap script ... ok
backend-api-1     | fail: Microsoft.AspNetCore.Server.Kestrel[13]
backend-api-1     |       Connection id "0HNEUJORJ9TM8", Request id "0HNEUJORJ9TM8:00000001": An unhandled exception was thrown by the application.
backend-api-1     |       Npgsql.NpgsqlException (0x80004005): Failed to connect to 172.21.0.2:5432
backend-api-1     |        ---> System.Net.Sockets.SocketException (111): Connection refused
backend-api-1     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
backend-api-1     |          at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|214_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.PoolingDataSource.<Get>g__RentAsync|33_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Postgres.PostgresConnection.OpenConnectionAsync() in /src/src/rinha-de-backend-2025.api/Infraestrutura/Postgres/PostgresConnection.cs:line 16
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Repositories.PaymentRepository.GetPaymentSummary(Nullable`1 startDate, Nullable`1 endDate) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Repositories/PaymentRepository.cs:line 18
backend-api-1     |          at rinha_de_backend_2025.api.Service.PaymentProcessor.GetSummaryAndAll(Nullable`1 startDate, Nullable`1 endDate) in /src/src/rinha-de-backend-2025.api/Service/PaymentProcessor.cs:line 27
backend-api-1     |          at rinha_de_backend_2025.api.Controllers.PaymentController.PaymentSummary(Nullable`1 from, Nullable`1 to) in /src/src/rinha-de-backend-2025.api/Controllers/PaymentController.cs:line 27
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
backend-api-1     |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
backend-api-1     |          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
backend-api-1     |          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
backend-api-1     |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
backend_database  | sh: locale: not found
backend_database  | 2025-08-18 21:28:47.226 UTC [35] WARNING:  no usable system locales were found
backend_database  | performing post-bootstrap initialization ... ok
backend_database  | initdb: warning: enabling "trust" authentication for local connections
backend_database  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
backend_database  | syncing data to disk ... ok
backend_database  | 
backend_database  | 
backend_database  | Success. You can now start the database server using:
backend_database  | 
backend_database  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
backend_database  | 
backend_database  | waiting for server to start....2025-08-18 21:28:50.045 UTC [47] LOG:  starting PostgreSQL 17.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
backend_database  | 2025-08-18 21:28:50.049 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
backend_database  | 2025-08-18 21:28:50.061 UTC [50] LOG:  database system was shut down at 2025-08-18 21:28:49 UTC
backend_database  | 2025-08-18 21:28:50.130 UTC [47] LOG:  database system is ready to accept connections
backend_database  |  done
backend_database  | server started
backend_database  | CREATE DATABASE
backend_database  | 
backend_database  | 
backend_database  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-schema.sql
backend_database  | CREATE TABLE
backend_database  | CREATE TABLE
backend_database  | CREATE INDEX
backend_database  | CREATE INDEX
backend_database  | INSERT 0 1
backend_database  | 
backend_database  | 
backend_database  | waiting for server to shut down....2025-08-18 21:28:50.730 UTC [47] LOG:  received fast shutdown request
backend_database  | 2025-08-18 21:28:50.734 UTC [47] LOG:  aborting any active transactions
backend_database  | 2025-08-18 21:28:50.824 UTC [47] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
backend_database  | 2025-08-18 21:28:50.824 UTC [48] LOG:  shutting down
backend_database  | 2025-08-18 21:28:50.827 UTC [48] LOG:  checkpoint starting: shutdown immediate
backend_database  | 2025-08-18 21:28:50.964 UTC [48] LOG:  checkpoint complete: wrote 935 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.093 s, sync=0.033 s, total=0.140 s; sync files=315, longest=0.004 s, average=0.001 s; distance=4289 kB, estimate=4289 kB; lsn=0/191D780, redo lsn=0/191D780
backend_database  | 2025-08-18 21:28:50.974 UTC [47] LOG:  database system is shut down
backend_database  |  done
backend_database  | server stopped
backend_database  | 
backend_database  | PostgreSQL init process complete; ready for start up.
backend_database  | 
backend_database  | 2025-08-18 21:28:51.058 UTC [1] LOG:  starting PostgreSQL 17.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
backend_database  | 2025-08-18 21:28:51.058 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
backend_database  | 2025-08-18 21:28:51.058 UTC [1] LOG:  listening on IPv6 address "::", port 5432
backend_database  | 2025-08-18 21:28:51.064 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
backend_database  | 2025-08-18 21:28:51.128 UTC [65] LOG:  database system was shut down at 2025-08-18 21:28:50 UTC
backend_database  | 2025-08-18 21:28:51.137 UTC [1] LOG:  database system is ready to accept connections
backend-api-2     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-2     |       Timeout occurred while processing payment with Default for correlation 133d9905-61b0-4527-be6b-0f69014ad380
backend-api-2     |       System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 0.8 seconds elapsing.
backend-api-2     |        ---> System.TimeoutException: The operation was canceled.
backend-api-2     |        ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
backend-api-2     |        ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
backend-api-2     |        ---> System.Net.Sockets.SocketException (125): Operation canceled
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
backend-api-2     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
backend-api-2     |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-2     |          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
backend-api-2     |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-2     |          at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
backend-api-2     |          at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
backend-api-2     |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
backend-api-2     |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 56
backend-api-1     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-1     |       Timeout occurred while processing payment with Default for correlation db28b7c8-1d34-417a-8476-9532590ea0fb
backend-api-1     |       System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 0.8 seconds elapsing.
backend-api-1     |        ---> System.TimeoutException: The operation was canceled.
backend-api-1     |        ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
backend-api-1     |        ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
backend-api-1     |        ---> System.Net.Sockets.SocketException (125): Operation canceled
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
backend-api-1     |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
backend-api-1     |          at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
backend-api-1     |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 56
backend-api-2     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-2     |       HTTP error occurred while processing payment with Default for correlation 727d4bb9-3830-400d-87d0-f9e4b57d47c0
backend-api-2     |       System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-1     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-1     |       HTTP error occurred while processing payment with Default for correlation decdc0e0-601b-4aa9-8960-9663f12fb4df
backend-api-1     |       System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-1     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-1     |       HTTP error occurred while processing payment with Fallback for correlation 4aef9410-0ab5-42bc-90d1-869571d91c2b
backend-api-1     |       System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-2     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-2     |       HTTP error occurred while processing payment with Fallback for correlation f4ba26b9-3e27-4f46-ab1b-b27fbdf69107
backend-api-2     |       System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-2     | fail: rinha_de_backend_2025.api.Infraestrutura.Workers.PaymentEventConsumer[0]
backend-api-2     |       An error occurred while processing the payment request.
backend-api-2     |       System.InvalidOperationException: Payment processing failed due to network error with Fallback
backend-api-2     |        ---> System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 78
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPaymentFallback(PaymentRequest request) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 17
backend-api-2     |          at rinha_de_backend_2025.api.Service.PaymentProcessor.PaymentProcessorFallback(PaymentRequest request) in /src/src/rinha-de-backend-2025.api/Service/PaymentProcessor.cs:line 20
backend-api-2     |          at rinha_de_backend_2025.api.Configurations.PaymentResiliencePolicyProvider.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext() in /src/src/rinha-de-backend-2025.api/Configurations/PaymentResiliencePolicyProvider.cs:line 28
backend-api-2     |       --- End of stack trace from previous location ---
backend-api-2     |          at Polly.Fallback.AsyncFallbackPolicy.<>c__DisplayClass3_0.<<ImplementationAsync>b__2>d.MoveNext()
backend-api-2     |       --- End of stack trace from previous location ---
backend-api-2     |          at Polly.Fallback.AsyncFallbackEngine.ImplementationAsync[TResult](Func`3 action, Context context, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, Func`3 onFallbackAsync, Func`4 fallbackAction, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-2     |          at Polly.AsyncPolicy.ExecuteInternalAsync(Func`3 action, Context context, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-2     |          at Polly.AsyncPolicy.ExecuteInternalAsync(Func`3 action, Context context, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-2     |          at rinha_de_backend_2025.api.Service.PaymentManager.SubmitPayment(PaymentRequest request, CancellationToken cancellationToken) in /src/src/rinha-de-backend-2025.api/Service/PaymentManager.cs:line 23
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Workers.PaymentEventConsumer.ExecuteAsync(CancellationToken stoppingToken) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Workers/PaymentEventConsumer.cs:line 20
backend-api-1     | fail: rinha_de_backend_2025.api.Infraestrutura.Workers.PaymentEventConsumer[0]
backend-api-1     |       An error occurred while processing the payment request.
backend-api-1     |       System.InvalidOperationException: Payment processing failed due to network error with Fallback
backend-api-1     |        ---> System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 78
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPaymentFallback(PaymentRequest request) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 17
backend-api-1     |          at rinha_de_backend_2025.api.Service.PaymentProcessor.PaymentProcessorFallback(PaymentRequest request) in /src/src/rinha-de-backend-2025.api/Service/PaymentProcessor.cs:line 20
backend-api-1     |          at rinha_de_backend_2025.api.Configurations.PaymentResiliencePolicyProvider.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext() in /src/src/rinha-de-backend-2025.api/Configurations/PaymentResiliencePolicyProvider.cs:line 28
backend-api-1     |       --- End of stack trace from previous location ---
backend-api-1     |          at Polly.Fallback.AsyncFallbackPolicy.<>c__DisplayClass3_0.<<ImplementationAsync>b__2>d.MoveNext()
backend-api-1     |       --- End of stack trace from previous location ---
backend-api-1     |          at Polly.Fallback.AsyncFallbackEngine.ImplementationAsync[TResult](Func`3 action, Context context, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, Func`3 onFallbackAsync, Func`4 fallbackAction, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-1     |          at Polly.AsyncPolicy.ExecuteInternalAsync(Func`3 action, Context context, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-1     |          at Polly.AsyncPolicy.ExecuteInternalAsync(Func`3 action, Context context, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-1     |          at rinha_de_backend_2025.api.Service.PaymentManager.SubmitPayment(PaymentRequest request, CancellationToken cancellationToken) in /src/src/rinha-de-backend-2025.api/Service/PaymentManager.cs:line 23
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Workers.PaymentEventConsumer.ExecuteAsync(CancellationToken stoppingToken) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Workers/PaymentEventConsumer.cs:line 20
backend-api-1     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-1     |       HTTP error occurred while processing payment with Fallback for correlation f21999a5-9b5f-44a6-9435-e10e9eae7195
backend-api-1     |       System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-2     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-2     |       HTTP error occurred while processing payment with Fallback for correlation 6e6417c6-6147-48ac-a1ee-fd57615a07de
backend-api-2     |       System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-1     | fail: rinha_de_backend_2025.api.Infraestrutura.Workers.PaymentEventConsumer[0]
backend-api-1     |       An error occurred while processing the payment request.
backend-api-1     |       System.InvalidOperationException: Payment processing failed due to network error with Fallback
backend-api-1     |        ---> System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 78
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPaymentFallback(PaymentRequest request) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 17
backend-api-1     |          at rinha_de_backend_2025.api.Service.PaymentProcessor.PaymentProcessorFallback(PaymentRequest request) in /src/src/rinha-de-backend-2025.api/Service/PaymentProcessor.cs:line 20
backend-api-1     |          at rinha_de_backend_2025.api.Configurations.PaymentResiliencePolicyProvider.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext() in /src/src/rinha-de-backend-2025.api/Configurations/PaymentResiliencePolicyProvider.cs:line 28
backend-api-1     |       --- End of stack trace from previous location ---
backend-api-1     |          at Polly.Fallback.AsyncFallbackPolicy.<>c__DisplayClass3_0.<<ImplementationAsync>b__2>d.MoveNext()
backend-api-1     |       --- End of stack trace from previous location ---
backend-api-1     |          at Polly.Fallback.AsyncFallbackEngine.ImplementationAsync[TResult](Func`3 action, Context context, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, Func`3 onFallbackAsync, Func`4 fallbackAction, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-1     |          at Polly.AsyncPolicy.ExecuteInternalAsync(Func`3 action, Context context, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-1     |          at Polly.AsyncPolicy.ExecuteInternalAsync(Func`3 action, Context context, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-1     |          at rinha_de_backend_2025.api.Service.PaymentManager.SubmitPayment(PaymentRequest request, CancellationToken cancellationToken) in /src/src/rinha-de-backend-2025.api/Service/PaymentManager.cs:line 23
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Workers.PaymentEventConsumer.ExecuteAsync(CancellationToken stoppingToken) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Workers/PaymentEventConsumer.cs:line 20
backend-api-2     | fail: rinha_de_backend_2025.api.Infraestrutura.Workers.PaymentEventConsumer[0]
backend-api-2     |       An error occurred while processing the payment request.
backend-api-2     |       System.InvalidOperationException: Payment processing failed due to network error with Fallback
backend-api-2     |        ---> System.Net.Http.HttpRequestException: Payment processing failed with status InternalServerError: Internal Server Error
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 70
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 78
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPaymentFallback(PaymentRequest request) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 17
backend-api-2     |          at rinha_de_backend_2025.api.Service.PaymentProcessor.PaymentProcessorFallback(PaymentRequest request) in /src/src/rinha-de-backend-2025.api/Service/PaymentProcessor.cs:line 20
backend-api-2     |          at rinha_de_backend_2025.api.Configurations.PaymentResiliencePolicyProvider.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext() in /src/src/rinha-de-backend-2025.api/Configurations/PaymentResiliencePolicyProvider.cs:line 28
backend-api-2     |       --- End of stack trace from previous location ---
backend-api-2     |          at Polly.Fallback.AsyncFallbackPolicy.<>c__DisplayClass3_0.<<ImplementationAsync>b__2>d.MoveNext()
backend-api-2     |       --- End of stack trace from previous location ---
backend-api-2     |          at Polly.Fallback.AsyncFallbackEngine.ImplementationAsync[TResult](Func`3 action, Context context, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, Func`3 onFallbackAsync, Func`4 fallbackAction, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-2     |          at Polly.AsyncPolicy.ExecuteInternalAsync(Func`3 action, Context context, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-2     |          at Polly.AsyncPolicy.ExecuteInternalAsync(Func`3 action, Context context, Boolean continueOnCapturedContext, CancellationToken cancellationToken)
backend-api-2     |          at rinha_de_backend_2025.api.Service.PaymentManager.SubmitPayment(PaymentRequest request, CancellationToken cancellationToken) in /src/src/rinha-de-backend-2025.api/Service/PaymentManager.cs:line 23
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Workers.PaymentEventConsumer.ExecuteAsync(CancellationToken stoppingToken) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Workers/PaymentEventConsumer.cs:line 20
backend-api-2     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-2     |       Timeout occurred while processing payment with Default for correlation 5d44c100-670a-4d6a-9c06-fd034b214f46
backend-api-2     |       System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 0.8 seconds elapsing.
backend-api-2     |        ---> System.TimeoutException: The operation was canceled.
backend-api-2     |        ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
backend-api-2     |        ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
backend-api-2     |        ---> System.Net.Sockets.SocketException (125): Operation canceled
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
backend-api-2     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
backend-api-2     |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-2     |          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
backend-api-2     |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-2     |          at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
backend-api-2     |          at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
backend-api-2     |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          --- End of inner exception stack trace ---
backend-api-2     |          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
backend-api-2     |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
backend-api-2     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 56
backend-api-1     | fail: rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient[0]
backend-api-1     |       Timeout occurred while processing payment with Default for correlation fb592e2e-b2f6-4547-898f-65e46e4299d4
backend-api-1     |       System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 0.8 seconds elapsing.
backend-api-1     |        ---> System.TimeoutException: The operation was canceled.
backend-api-1     |        ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
backend-api-1     |        ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
backend-api-1     |        ---> System.Net.Sockets.SocketException (125): Operation canceled
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
backend-api-1     |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
backend-api-1     |          at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
backend-api-1     |          at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
backend-api-1     |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          --- End of inner exception stack trace ---
backend-api-1     |          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
backend-api-1     |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
backend-api-1     |          at rinha_de_backend_2025.api.Infraestrutura.Clients.PaymentGatewayClient.ProcessPayment(PaymentRequest request, service_used serviceType) in /src/src/rinha-de-backend-2025.api/Infraestrutura/Clients/PaymentGatewayClient.cs:line 56
backend_database  | 2025-08-18 21:33:51.227 UTC [63] LOG:  checkpoint starting: time
backend_database  | 2025-08-18 21:33:56.034 UTC [63] LOG:  checkpoint complete: wrote 76 buffers (0.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.688 s, sync=0.106 s, total=4.807 s; sync files=25, longest=0.084 s, average=0.005 s; distance=2328 kB, estimate=2328 kB; lsn=0/1B8C278, redo lsn=0/1B63880
[Kload_balancer exited with code 0
backend_database  | 2025-08-18 21:34:10.226 UTC [137] LOG:  could not send data to client: Broken pipe
backend_database  | 2025-08-18 21:34:10.226 UTC [137] FATAL:  connection to client lost
[Kbackend-api-1 exited with code 137
[Kbackend-api-2 exited with code 137
backend_database  | 2025-08-18 21:34:10.494 UTC [1] LOG:  received fast shutdown request
backend_database  | 2025-08-18 21:34:10.497 UTC [1] LOG:  aborting any active transactions
backend_database  | 2025-08-18 21:34:10.501 UTC [1] LOG:  background worker "logical replication launcher" (PID 68) exited with exit code 1
backend_database  | 2025-08-18 21:34:10.501 UTC [63] LOG:  shutting down
backend_database  | 2025-08-18 21:34:10.504 UTC [63] LOG:  checkpoint starting: shutdown immediate
backend_database  | 2025-08-18 21:34:10.545 UTC [63] LOG:  checkpoint complete: wrote 1469 buffers (9.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.022 s, sync=0.008 s, total=0.045 s; sync files=9, longest=0.004 s, average=0.001 s; distance=617 kB, estimate=2157 kB; lsn=0/1BFDEC8, redo lsn=0/1BFDEC8
backend_database  | 2025-08-18 21:34:10.555 UTC [1] LOG:  database system is shut down
log truncated at line 1000
